backend:
  name: git-gateway
  branch: main
  publish_mode: editorial_workflow

# Add the route to your images, so Netlify CMS knows where to save uploads to.
media_folder: "src/assets/img"
public_foder: "/assets/img"

# Add your collections. Here's an example of multiple collections: 
collections:
# Iphone
  - label: "Iphone" 
    name: "services_iphone"
    folder: "src/service_iphone" # Where the new posts should be saved to
    media_folder: "img/"
    public_folder: "/service_iphone/img/"
    create: true # This allows you to create new instances in the CMS
    slug: "{{slug}}" 
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: false }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Opis", name: "description", widget: "text" }



# Ipad
  - label: "Ipad"   
    name: "services_ipad"
    folder: "src/service_ipad" # Where the new posts should be saved to
    media_folder: "img/"
    public_folder: "/service_ipad/img/"
    create: true # This allows you to create new instances in the CMS
    slug: "{{slug}}" 
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: false }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Opis", name: "description", widget: "text" }



# Mackbook
  - label: "Mackbook"   
    name: "services_mackbook"
    folder: "src/service_mackbook" # Where the new posts should be saved to
    media_folder: "img/"
    public_folder: "/service_mackbook/img/"
    create: true # This allows you to create new instances in the CMS
    slug: "{{slug}}" 
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: false }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Opis", name: "description", widget: "text" }


# Watch
  - label: "Watch"   
    name: "services_watch"
    folder: "src/service_watch" # Where the new posts should be saved to
    media_folder: "img/"
    public_folder: "/service_watch/img/"
    create: true # This allows you to create new instances in the CMS
    slug: "{{slug}}" 
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: false }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Opis", name: "description", widget: "text" }

