backend:
  name: git-gateway
  branch: main
  publish_mode: editorial_workflow

local_backend: true

# Add the route to your images, so Netlify CMS knows where to save uploads to.
media_folder: "src/assets/img"
public_foder: "/assets/img"

# Posts
collections:
  - name: "posts"
    label: "Wpisy" 
    folder: "src/blog"
    media_folder: "src/assets/img"
    public_folder: "/assets/img"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Obrazek", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

# Telefony
  - label: "Telefony" 
    name: "services_phone"
    folder: "src/service_phone" # Where the new posts should be saved to
    media_folder: "img/"
    public_folder: "/service_phone/img/"
    create: true # This allows you to create new instances in the CMS
    slug: "{{slug}}" 
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: false }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Opis", name: "description", widget: "text" }



# Tablet
  - label: "Tablety"   
    name: "services_tablet"
    folder: "src/service_tablet" # Where the new posts should be saved to
    media_folder: "img/"
    public_folder: "/service_tablet/img/"
    create: true # This allows you to create new instances in the CMS
    slug: "{{slug}}" 
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: false }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Opis", name: "description", widget: "text" }



# Computer
  - label: "Komputery"   
    name: "services_computer"
    folder: "src/service_computer" # Where the new posts should be saved to
    media_folder: "img/"
    public_folder: "/service_computer/img/"
    create: true # This allows you to create new instances in the CMS
    slug: "{{slug}}" 
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: false }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Opis", name: "description", widget: "text" }


# Laptop
  - label: "Laptopy"   
    name: "services_laptop"
    folder: "src/service_laptop" # Where the new posts should be saved to
    media_folder: "img/"
    public_folder: "/service_laptop/img/"
    create: true # This allows you to create new instances in the CMS
    slug: "{{slug}}" 
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: false }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Opis", name: "description", widget: "text" }

